title: MiniApp Documentation for NEOM SuperApp 
description: MiniApp Documentation for NEOM SuperApp 
theme: just-the-docs

url: https://neos-critical.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
