title: NEOM MiniApp Docs
description: MiniApp Documentation for NEOM SuperHub
theme: just-the-docs

url: https://neos-critical.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
